# Generated by Django 5.2.8 on 2025-11-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(help_text='사용자가 입력한 문자 원문')),
                ('result_label', models.CharField(help_text='모델이 판별한 결과 (예: 위험, 안전)', max_length=10)),
                ('result_percent', models.FloatField(help_text='모델이 계산한 확률 (예: 98.5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
