# Generated by Django 5.2.8 on 2025-11-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationlog',
            options={'ordering': ['-created_at'], 'verbose_name': '피싱 탐지 로그', 'verbose_name_plural': '피싱 탐지 로그'},
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='result_label',
            field=models.CharField(db_index=True, help_text='모델이 판별한 결과 (예: 위험, 안전)', max_length=50),
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='result_percent',
            field=models.FloatField(help_text='모델이 계산한 확률 (0~100)'),
        ),
        migrations.AlterModelTable(
            name='communicationlog',
            table='communication_logs',
        ),
    ]
